version: "3.8"
services:
  client:
      build: ./client
      depends_on:
        - upload
        - download
      environment:
        - UPLOAD_URL=http://upload:5000
        - DOWNLOAD_URL=http://download:5003
      volumes:
        - ./client:/app
      stdin_open: true
      tty: true
  upload:
    build: ./services/upload
    ports:
      - "5000:5000"
    depends_on:
      - storage
      - metadata
  download:
    build: ./services/download
    ports:
      - "5003:5003"
    depends_on:
      - storage
      - metadata
  metadata:
    build: ./metadata
    volumes:
      - metadata_data:/data
    ports:
      - "5001:5001"

  storage:
    build: ./storage
    volumes:
      - storage_data:/storage
    ports:
      - "5002:5002"

  backup:
    build: ./backup
    volumes:
      - metadata_data:/metadata
      - storage_data:/storage
      - backup_data:/backup

volumes:
  metadata_data:
  storage_data:
  backup_data:
